server:
  port: 8088

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      ddl-auto: update
    generate-ddl: true
  flyway:
    enabled: true
    url: ${app.datasource.url}
    password: ${app.datasource.password}
    user: ${app.datasource.username}

  datasource:
    url: ${app.datasource.url}
    username: ${app.datasource.username}
    password: ${app.datasource.password}
    driver-class-name: org.postgresql.Driver

app:
  datasource:
    url: jdbc:postgresql://localhost:5432/uni_app
    username: uniUser
    password: ChangeIt2024
